service: pie

frameworkVersion: "3"

plugins:
  - serverless-plugin-typescript

provider:
  name: aws
  runtime: nodejs16.x
  stage: ${env:ENV_STAGE}

functions:
  hello:
    handler: src/handler/Something.HANDLER
